[OBEZS] Add label

diff --git a/plerkle_snapshot/Makefile b/plerkle_snapshot/Makefile
--- a/plerkle_snapshot/Makefile
+++ b/plerkle_snapshot/Makefile
@@ -4,7 +4,7 @@ G = \033[1;92m#   GREEN
 Y = \033[1;93m#   YELLOW
 R = \033[1;31m#   RED
 M = \033[1;95m#   MAGENTA
-C=  \033[1;96m#   CYAN
+C = \033[1;96m#   CYAN
 K = \033[K#       ERASE END OF LINE
 D = \033[0m#      DEFAULT
 A = \007#         BEEP
@@ -12,11 +12,12 @@ A = \007#         BEEP
 .PHONY: build push clean download stream
 
 SHELL := /bin/bash
-#APP=$(shell basename -s .git $(shell git remote get-url origin))
-#REGISTRY=ghcr.io/obezsmertnyi
-VERSION=$(shell git describe --tags --abbrev=0)
-BASEDIR = ./snapshot/*.tar.zst
-BASEPATH=${REGISTRY}/${APP}:${VERSION}
+#APP = solana-snapshot-etl
+#REGISTRY = ghcr.io/metaplex-foundation
+REPO_NAME = $(shell basename -s .git $(shell git remote get-url origin))
+VERSION = $(shell git describe --tags --abbrev=0)
+BASEDIR = ./snapshot/
+BASEPATH = ${REGISTRY}/${REPO_NAME}/${APP}:${VERSION}
 
 build:
 	@echo -e "${M}Starting build for Docker image: ${APP}${D}"
@@ -33,8 +34,8 @@ build:
 push:
 	@echo -e "${M}Pushing Docker image to the registry: ${BASEPATH}${D}"
 	@docker push ${BASEPATH} || { echo -e "${R}Error: Failed to push the image.${D}"; exit 1; }
-	@docker tag ${BASEPATH} ${REGISTRY}/${APP}:latest
-	@docker push ${REGISTRY}/${APP}:latest || { echo -e "${R}Error: Failed to push the 'latest' tag.${D}"; exit 1; }
+	@docker tag ${BASEPATH} ${REGISTRY}/${REPO_NAME}/${APP}:latest
+	@docker push ${REGISTRY}/${REPO_NAME}/${APP}:latest || { echo -e "${R}Error: Failed to push the 'latest' tag.${D}"; exit 1; }
 	@echo -e "${G}Image pushed successfully!${D}"
 
 clean:
@@ -53,26 +54,4 @@ download:
 	@docker run -it --rm -v $(PWD)/snapshot:/snapshot --user $(id -u):$(id -g) c29r3/solana-snapshot-finder:latest --snapshot_path /snapshot
 
 stream:
-        @INGESTER_RPC_HOST=$$(docker exec ingester env | grep INGESTER_RPC_HOST | cut -d "=" -f2); \
-        docker exec -it synchronizer sh -c ' \
-                echo "\033[1;94mSYNCHRONIZER_METRICS_PORT: $$SYNCHRONIZER_METRICS_PORT\033[0m"; \
-                echo "\033[1;94mINGESTER_RPC_HOST: $$INGESTER_RPC_HOST\033[0m"; \
-                while true; do \
-                        # Get current Solana slot \
-                        solana_slot=$$(curl -s -X POST -H "Content-Type: application/json" -d '\''{"jsonrpc": "2.0","id": 1,"method": "getSlot","params": [{"commitment": "processed"}]}'\'' $$INGESTER_RPC_HOST | grep -oP "(?<=\"result\":)[0-9]+"); \
-                        echo "\033[1;92mSolana slot: $$solana_slot\033[0m"; \
-                        # Get last synchronized slot from synchronizer \
-                        synchronizer_slot=$$(curl -s localhost:$$SYNCHRONIZER_METRICS_PORT/metrics | grep "synchronizer_last_synchronized_slot{name=\"last_synchronized_slot\"}" | awk '\''{print $$2}'\''); \
-                        echo "\033[1;92mSynchronizer last synchronized slot: $$synchronizer_slot\033[0m"; \
-                        # Calculate the difference between Solana and synchronizer slots \
-                        difference=$$((solana_slot - synchronizer_slot)); \
-                        echo "\033[1;93mDifference: $$difference slots\033[0m"; \
-                        # Check if the difference is below threshold \
-                        if [ "$$difference" -lt 50 ]; then \
-                                echo  "\033[1;92mSlot difference is below threshold. Exiting loop.\033[0m"; \
-                                break; \
-                        fi; \
-                        # Wait before next iteration \
-                        echo "\033[1;95mWaiting for 5 seconds before next check...\033[0m"; \
-                        sleep 5; \
-                done 2>/dev/null'
+	@docker run -p 5000:5000 --rm -v ${BASEDIR}:/snapshots -e TCP_PORT=5000 -e TCP_MIN_SUBSCRIBERS=1 ${BASEPATH}
